FROM ubuntu
RUN apt-get update -y
RUN apt-get install -y nginx
WORKDIR /usr/share/nginx/html
COPY index.html  /usr/share/nginx/html
EXPOSE 8080
ADD compressedfile.tar.gz /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"] 
